# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20171015_0331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['school_name']},
        ),
        migrations.AddField(
            model_name='enquiry',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
