# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 18:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20171026_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='description',
            new_name='message',
        ),
    ]
