# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 23:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20171026_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolcomment',
            old_name='description',
            new_name='message',
        ),
        migrations.AddField(
            model_name='schoolcomment',
            name='rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
