# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 00:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20171029_1749'),
        ('app', '0007_auto_20171029_2323'),
    ]

    operations = [
    ]
