# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_merge_20171030_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Answered')], default='P', max_length=1),
        ),
    ]
