# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_enquiry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='express_nonaff_lower',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='express_nonaff_upper',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='lat',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='lng',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.ImageField(default='media/None/no-img.jpg', upload_to='media/'),
        ),
        migrations.AddField(
            model_name='school',
            name='normal_academic_nonaff_lower',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='normal_academic_nonaff_upper',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='normal_technical_nonaff_lower',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='normal_technical_nonaff_upper',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
