# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20171030_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='logo',
        ),
        migrations.AddField(
            model_name='school',
            name='logo_name',
            field=models.CharField(default='no-img.jpg', max_length=300),
        ),
    ]
