# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20171114_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulerlog',
            name='other_school',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.OtherSchool'),
        ),
    ]
